### ISSUE TITLE
geo_address() data drift from duplicate addresses

### ISSUE THREAD

**Issue by MuellerMatthew** [austensen/geoclient#11]
When using `dplyr::mutate(df, zip2= geo_address(num, street, borough)[["zipCode"]])` to return a single updated geoclient field for a list of addresses I noticed that when the script passed a record containing  an address that appears in the dataset more than once, the returned field value would also be added to the following row of data.  This messes up all subsequent records between each pair of duplicate addresses as the returned data is attached to the wrong row.

Below is a short example with 6 records I have added 1 duplicate address to the list and I have included the expected zip code with the script returning a second zip code.
```r
library(dplyr)
library(geoclient)

building <- c("1", "3", "2", "3", "3", "5")
street <- c("PRINCE ST", "GREENWICH AVE", "E 61ST ST", "E 48TH ST", "GREENWICH AVE", "AVENUE A")
borough <- c("MANHATTAN", "MANHATTAN", "MANHATTAN", "MANHATTAN", "MANHATTAN", "MANHATTAN")
zip1 <-  c("10012", "10014", "10065", "10017", "10014", "10009")

df <- data.frame(building,street,borough,zip1)

df2 <- dplyr::mutate(df, zip2 = geo_address(building, street, borough)[["zipCode"]])
head(df2)
#>   building        street   borough  zip1  zip2
#> 1        1     PRINCE ST MANHATTAN 10012 10012
#> 2        2     E 61ST ST MANHATTAN 10065 10065
#> 3        3 GREENWICH AVE MANHATTAN 10014 10014
#> 4        3     E 48TH ST MANHATTAN 10017 10014
#> 5        3 GREENWICH AVE MANHATTAN 10014 10017
#> 6        5      AVENUE A MANHATTAN 10009 10009
```
Note rows 2 and 5 contain the same address, but the returned zip codes are different as the zip code for row 5 is on row 3, and the zip codes for row 3 and 4 have both shifted down a row.

**Comment by austensen** [comment]
Hey @MuellerMatthew, thanks so much for letting me know about this issue and taking the time to set up this reproducible example. It made it much easier to see the issue and incorporate as a new unit test for the package. I've fixed the issue in the above commit and so you should be all good now. Just let me know if you run into any further problems.
